### ISSUE TITLE
infografai

### ISSUE THREAD

**Issue by Azucena-Tejeda** [SistemasTecTlaxiaco/practica-de-hilos-Azucena-Tejeda#2]
[REPORTE HILOS.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-hilos-Azucena-Tejeda/files/6498166/REPORTE.HILOS.pdf)

**Comment by javiern-778** [comment]
18 le hizo falta mas imágenes

**Comment by josealfredo79** [comment]
Bien hecho y revisado
